### ISSUE TITLE
main.cpp:13: error: C2065: “M_PI”: 未声明的标识符

### ISSUE THREAD

**Issue by ConquerLearn** [Przemekkkth/AnalogClock_Qt-Cpp#2]
main.cpp:13: error: C2065: “M_PI”: 未声明的标识符

**Comment by Przemekkkth** [comment]
Hi @mrquan3014,
M_PI is a constant from cmath. This describes PI value. You can replace it to: 3.141592f. 
Best

**Comment by ConquerLearn** [comment]
Thanks
